services:
  db:
    image: postgres
    restart: always
    environment:
       POSTGRES_USER: admin
       POSTGRES_PASSWORD: admin
       POSTGRES_DB: urlDb
    
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgressql/data

volumes:
  db_data: